# Generated by Django 6.0.3 on 2026-04-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('TOTEM', 'Totem'), ('BALCAO', 'Balcão')], max_length=20)),
                ('status', models.CharField(choices=[('CRIADO', 'Criado'), ('PAGO', 'Pago'), ('EM_PREPARO', 'Em preparo'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='CRIADO', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.produto')),
            ],
        ),
    ]
